<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login Test"
           tests="8"
           failures="1"
           errors="0"
           skipped="6"
           time="25.340">
    <properties></properties>

            <testcase
                name="closeBrowser"
                time="0.000"
                classname="testcases.TestUserLogin">

            <failure type="java.lang.NullPointerException" message="(null)">
                <![CDATA[java.lang.NullPointerException
                testcases.Base.closeBrowser(Base.java:72)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)org.testng.internal.Invoker.invokeMethod(Invoker.java:646)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)org.testng.TestRunner.privateRun(TestRunner.java:648)org.testng.TestRunner.run(TestRunner.java:505)org.testng.SuiteRunner.runTest(SuiteRunner.java:455)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)org.testng.SuiteRunner.run(SuiteRunner.java:364)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)org.testng.TestNG.runSuitesLocally(TestNG.java:1137)org.testng.TestNG.runSuites(TestNG.java:1049)org.testng.TestNG.run(TestNG.java:1017)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>

            <testcase
                name="setupReports"
                time="0.0"
                classname="testcases.TestUserLogin">
            </testcase>
            <testcase
                name="recordResults"
                time="0.0"
                classname="testcases.TestUserLogin">
            </testcase>
            <testcase
                name="browserLaunch"
                time="0.0"
                classname="testcases.TestUserLogin">
            </testcase>
            <testcase
                name="recordResults"
                time="0.0"
                classname="testcases.TestUserLogin">
            </testcase>
            <testcase
                name="closeBrowser"
                time="0.0"
                classname="testcases.TestUserLogin">
            </testcase>
            <testcase
                name="tc0007_invalid_email_login_test"
                time="0.0"
                classname="testcases.TestUserLogin">
            </testcase>

            <testcase
                name="tc0006_login_user_test"
                time="25.340"
                classname="testcases.TestUserLogin">
            </testcase>
</testsuite>
